name: Build APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Check project files
        run: |
          pwd
          ls -la
          echo "-----"
          find . -maxdepth 2 -type f | sort

          - name: Create debug keystore
        run: |
          mkdir -p ~/.android
          keytool -genkeypair \
            -v \
            -keystore ~/.android/debug.keystore \
            -storepass android \
            -alias androiddebugkey \
            -keypass android \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=Android Debug,O=Android,C=US"

          cp ~/.android/debug.keystore ./debug.keystore

      - name: Build APK
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug

      - name: Find APK
        run: |
          echo "Searching for APK..."
          find . -type f -name "*.apk" -print

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AI-NOTE-AI-APK
          path: "**/*.apk"
          if-no-files-found: error
